CREATE DATABASE GetCake;
GO

USE GetCake;
GO

CREATE TABLE PRODUTO(
	ID_PRODUTO INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(100) NOT NULL,
	VALOR DECIMAL(10, 2),
	DESCRICAO VARCHAR(200),
);
GO

CREATE TABLE CARRINHO(
	ID_CARRINHO INT PRIMARY KEY IDENTITY(1,1),
	ID_PRODUTO INT NOT NULL,
);
GO

ALTER TABLE CARRINHO ADD CONSTRAINT FK_PROD_CAR
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO);
GO

CREATE TABLE CLIENTE(
	ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
	NM_CLIENTE VARCHAR(60) NOT NULL,
	TIPO_CLIENTE CHAR(1) NOT NULL,
    CHECK (TIPO_CLIENTE IN ('F','J')),
    CPF_CNPJ VARCHAR(20) NOT NULL UNIQUE,
);
GO

CREATE TABLE FUNCIONARIO(
	ID_FUNCIONARIO INT PRIMARY KEY IDENTITY(1,1),
	NM_FUNCIONARIO VARCHAR (50) NOT NULL,
	CARGO_FUNCIONARIO VARCHAR(20) NOT NULL,
	CHECK (CARGO_FUNCIONARIO IN ('ADMINISTRACAO','COZINHA','ATENDIMENTO')),
	SAL_FUNCIONARIO DECIMAL(18,2) NOT NULL,
	DT_ADMISSAO DATETIME NOT NULL,
    DT_DEMISSAO DATETIME,
    STATUS_FUNCIONARIO CHAR(1) NOT NULL,
	CHECK (STATUS_FUNCIONARIO IN ('A','I')),
);
GO

CREATE TABLE ENDERECO (
	ID_ENDERECO INT PRIMARY KEY IDENTITY(1,1),
	CIDADE VARCHAR(25) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    RUA VARCHAR(25),
	QUADRA INT,
    LOTE INT,
    NUMERO INT,
    ID_END_CLIENTE INT,
);
GO

ALTER TABLE ENDERECO ADD CONSTRAINT FK_END_CLNT
FOREIGN KEY(ID_END_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
GO

CREATE TABLE TELEFONE (
	ID_TELEFONE INT PRIMARY KEY IDENTITY(1,1),
	TIPO_TEL CHAR(3) NOT NULL,
	CHECK(TIPO_TEL IN('RES','CEL','EMP')),
    NUM1 VARCHAR(15) NOT NULL,
    NUM2 VARCHAR(15),
    NUM3 VARCHAR(15),
    ID_TEL_CLIENTE INT,
);
GO

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TEL_CLNT
FOREIGN KEY(ID_TEL_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
GO